config/routes.rb
QualityCloud::Application.routes.draw do

  resources :question_answers

  resources :template_answers

  resources :question_possible_answers

  resources :questions

  resources :questions_sections

  resources :templates do
    resources :questions
  end

  get 'calls/:call_id/notes' => "call_notes#call_notes"
  resources :call_notes

  get '/users/:user_id/saved_search_tabs' => "saved_search_tabs#user_saved_tabs"
  get '/users/current_user_saved_search_tabs' => "saved_search_tabs#current_user_saved_tabs"
  resources :saved_search_tabs

  match '/organization' => "home#personal", as: :personal_tab
  match '/administration' => "home#administration", as: :administration_tab
  match '/search' => "home#search", as: :search_tab
  get '/settings' => "home#settings", as: :settings_tab
  
  resources :roles do
    member do
      put :set_permissions
    end
  end
  
  match "/permissions" => "roles#permissions"

  resources :groups do
    resources :users, only: [] do
      collection do
        get "/", action: :group_members
      end
    end
  end

  get 'calls/download_calls' => "calls#download_calls"
  get 'calls/:id/stream_video' => "calls#stream_video"
  get 'calls/:id/stream_audio' => "calls#stream_audio"
  match '/calls/search' => "calls#search"
  match '/calls/load_calls' => "calls#load_calls"
  resources :calls do 
    member do
      get :status, :show_popup
    end
  end

  resources :dashboard, only: [ :index ]
  resources :searches, only: [ :index, :create ], controller: :search, path: '/search'

  get '/admin/users/:id/user_avatar/:type' => "users#user_avatar"
  get '/admin/users/user_names' => "users#user_names"
  scope :admin, path: '/admin' do
    resources :users do
      collection { post :import }
    end
  end
  
  devise_for :users, :controllers => { :passwords => "passwords" }
  authenticated :user do
    root :to => 'home#search'
  end
  get "home/email_confirmation" => "home#email_confirmation"

  unauthenticated :user do
    devise_scope :user do 
      get "/" => "devise/sessions#new"
    end
  end

  resources :assigned_roles
  resources :role_accesses

end

app/views/shared/_header.html.haml
.top
  .logo-banner
    %img{:alt => "logo", :src => "assets/qc-logo-banner.png"}/


/ .navbar.navbar
/   .navbar-inner
/     .container
/       .pull-left
/         = image_tag('logo.png')
/       .pull-right
/         = link_to 'Quality Cloud', root_path, class: 'brand'
/ - if user_signed_in?
/   .subnav.subnav-fixed
/     .container
/       %ul.pull-right.nav.nav-pills
/         %li
/           = link_to current_user.email, edit_user_registration_path
/         %li
/           = link_to 'Sign out', destroy_user_session_path, method: :delete

app/views/shared/_lower_sidebar.html.haml
.left-buttons
  
  / -if current_user.has_permissions? [:show_settings_tab]
  .side_button.seting-icon.settings-side_button{ class: "#{'active' if @selected == :settings}" }
    = link_to 'Settings', settings_tab_path 

  / -if current_user.has_permissions? [:show_reporting_tab]
  .side_button.report-icon{ class: "#{'active' if @selected == :reporting}" }
    %a{ href: "javascript:;"} Reporting

  / -if current_user.has_permissions? [:show_admin_tab]
  .side_button.admin-icon{ class: "#{'active' if @selected == :administration}", disabled: true }
    = link_to 'Administration    ', administration_tab_path

app/views/shared/_sidebar.html.haml
= render 'shared/upper_sidebar'

- if @selected == :search
  %span.left-buttons#below_side_bar{:style=>"margin-top: 0px;"}

= render 'shared/lower_sidebar'

app/views/shared/_upper_sidebar.html.haml
.left-buttons
  -if current_user.has_permissions? [:show_dashboard_tab]
    .side_button.dashbord-icon{ class: "#{'active' if @selected == :dashboard}", disabled: true } Dashboard
    
  -if current_user.has_permissions? [:show_organization_tab]
    .side_button.org-icon{ class: "#{'active' if @selected == :personal}" }
      = link_to 'Organization', personal_tab_path

  / .side_button{ class: "#{'active' if @selected == :dashboard}", disabled: true }
  / = link_to 'Dashboard', root_path
  -if current_user.has_permissions? [:show_search_tab]
    .side_button.srch-icon#search_sidebar{ class: "#{'active' if @selected == :search}" }
      = link_to 'Search', search_tab_path

  / .side_button
  /   = link_to 'Settings', edit_user_registration_path
    
/ .well.sidebar-nav-fixed
/   %ul.nav.nav-list
/     %li{ class: "#{'active' if @selected == :personal}" }
/       = link_to 'Personal', personal_tab_path
/     %li{ class: "#{'active' if @selected == :dashboard}" }
/       = link_to 'Dashboard', root_path
/     %li{ class: "#{'active' if @selected == :search}" }
/       = link_to 'Search', search_tab_path
/     %li{ class: "#{'active' if devise_controller? }" }
/       = link_to 'Settings', edit_user_registration_path

app/views/shared/_user_info.html.haml
.welcome-right.fl
  .icon.fl.js-open-profile{:title => "Click to edit your profile"}
    %img#user_img_header{:alt => "icon", :height => "21", :src => current_user.avatar.url(:thumb), :width => "23"}/
  .wecometext.fl#welcome_user_header.js-open-profile{:title => "Click to edit your profile"}="Welcome, #{current_user.full_name}"
  .logout-text.fl
    = link_to 'Logout', destroy_user_session_path, method: :delete

app/views/shared/_user_profile.html.haml
#user_profile_modal.no-padding-popup.modal.hide-it.fade.videoPopup-new{ :style => "left: 50%;width: 612px !important;"}
  .heading_new
    User Profile
    .fr.Mt.Mr{:style => "margin-top: 5px;"}
      %a.js-close-profile{:href => "#"}
        %img{:alt => "", :height => "14", :src => "images/can-btn.png", :width => "12"}
  #user_profile_form.modal-body.js-user-form.user-modal-content
    = render "users/user_profile_form"
  .popup-bottom.fl{:style => "width: 610px !important;"}
    .bottom-button.fr.Mr25#submit_save_form{:style => "width:103px;cursor:pointer;"}
      %a{:href => "javascript:;"} Save
    .bottom-button.fr.Mr10#submit_apply_form{:style => "width:103px;cursor:pointer;"}
      %a{:href => "javascript:;"} Apply
    .bottom-button.fr.Mr10.js-close-profile{:style => "width:105px;cursor:pointer;"}
      %a{:href => "javascript:;"} Cancel