config/routes.rb
QualityCloud::Application.routes.draw do

  resources :question_answers

  resources :template_answers

  resources :question_possible_answers

  resources :questions

  resources :questions_sections

  resources :templates do
    resources :questions
  end

  get 'calls/:call_id/notes' => "call_notes#call_notes"
  resources :call_notes

  get '/users/:user_id/saved_search_tabs' => "saved_search_tabs#user_saved_tabs"
  get '/users/current_user_saved_search_tabs' => "saved_search_tabs#current_user_saved_tabs"
  resources :saved_search_tabs

  match '/organization' => "home#personal", as: :personal_tab
  match '/administration' => "home#administration", as: :administration_tab
  match '/search' => "home#search", as: :search_tab
  get '/settings' => "home#settings", as: :settings_tab
  
  resources :roles do
    member do
      put :set_permissions
    end
  end
  
  match "/permissions" => "roles#permissions"

  resources :groups do
    resources :users, only: [] do
      collection do
        get "/", action: :group_members
      end
    end
  end

  get 'calls/download_calls' => "calls#download_calls"
  get 'calls/:id/stream_video' => "calls#stream_video"
  get 'calls/:id/stream_audio' => "calls#stream_audio"
  match '/calls/search' => "calls#search"
  match '/calls/load_calls' => "calls#load_calls"
  resources :calls do 
    member do
      get :status, :show_popup
    end
  end

  resources :dashboard, only: [ :index ]
  resources :searches, only: [ :index, :create ], controller: :search, path: '/search'

  get '/admin/users/:id/user_avatar/:type' => "users#user_avatar"
  get '/admin/users/user_names' => "users#user_names"
  scope :admin, path: '/admin' do
    resources :users do
      collection { post :import }
    end
  end
  
  devise_for :users, :controllers => { :passwords => "passwords" }
  authenticated :user do
    root :to => 'home#search'
  end
  get "home/email_confirmation" => "home#email_confirmation"

  unauthenticated :user do
    devise_scope :user do 
      get "/" => "devise/sessions#new"
    end
  end

  resources :assigned_roles
  resources :role_accesses

end

app/models/question_answer.rb
class QuestionAnswer < ActiveRecord::Base

  # Associations
  belongs_to :template_answer
  belongs_to :question
  belongs_to :user

  # Attributes
  attr_accessible :answer, :weight
  
end

# belongs_to template_answer
# belongs_to question
# belongs_to user: who answered it
# answer 
# weight: as integer

app/controllers/question_answers_controller.rb
class QuestionAnswersController < ApplicationController
  # GET /question_answers
  # GET /question_answers.json
  def index
    @question_answers = QuestionAnswer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @question_answers }
    end
  end

  # GET /question_answers/1
  # GET /question_answers/1.json
  def show
    @question_answer = QuestionAnswer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question_answer }
    end
  end

  # GET /question_answers/new
  # GET /question_answers/new.json
  def new
    @question_answer = QuestionAnswer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question_answer }
    end
  end

  # GET /question_answers/1/edit
  def edit
    @question_answer = QuestionAnswer.find(params[:id])
  end

  # POST /question_answers
  # POST /question_answers.json
  def create
    @question_answer = QuestionAnswer.new(params[:question_answer])

    respond_to do |format|
      if @question_answer.save
        format.html { redirect_to @question_answer, notice: 'Question answer was successfully created.' }
        format.json { render json: @question_answer, status: :created, location: @question_answer }
      else
        format.html { render action: "new" }
        format.json { render json: @question_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /question_answers/1
  # PUT /question_answers/1.json
  def update
    @question_answer = QuestionAnswer.find(params[:id])

    respond_to do |format|
      if @question_answer.update_attributes(params[:question_answer])
        format.html { redirect_to @question_answer, notice: 'Question answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_answers/1
  # DELETE /question_answers/1.json
  def destroy
    @question_answer = QuestionAnswer.find(params[:id])
    @question_answer.destroy

    respond_to do |format|
      format.html { redirect_to question_answers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/question_answers_helper.rb
module QuestionAnswersHelper
end

app/views/question_answers/_form.html.haml
= form_for @question_answer do |f|
  - if @question_answer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question_answer.errors.count, "error")} prohibited this question_answer from being saved:"
      %ul
        - @question_answer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :template_answer
    = f.text_field :template_answer
  .field
    = f.label :question
    = f.text_field :question
  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :answer
    = f.text_field :answer
  .field
    = f.label :weight
    = f.number_field :weight
  .actions
    = f.submit 'Save'

app/views/question_answers/edit.html.haml
%h1 Editing question_answer

= render 'form'

= link_to 'Show', @question_answer
\|
= link_to 'Back', question_answers_path

app/views/question_answers/index.html.haml
%h1 Listing question_answers

%table
  %tr
    %th Template answer
    %th Question
    %th User
    %th Answer
    %th Weight
    %th
    %th
    %th

  - @question_answers.each do |question_answer|
    %tr
      %td= question_answer.template_answer
      %td= question_answer.question
      %td= question_answer.user
      %td= question_answer.answer
      %td= question_answer.weight
      %td= link_to 'Show', question_answer
      %td= link_to 'Edit', edit_question_answer_path(question_answer)
      %td= link_to 'Destroy', question_answer, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Question answer', new_question_answer_path

app/views/question_answers/new.html.haml
%h1 New question_answer

= render 'form'

= link_to 'Back', question_answers_path

app/views/question_answers/show.html.haml
%p#notice= notice

%p
  %b Template answer:
  = @question_answer.template_answer
%p
  %b Question:
  = @question_answer.question
%p
  %b User:
  = @question_answer.user
%p
  %b Answer:
  = @question_answer.answer
%p
  %b Weight:
  = @question_answer.weight

= link_to 'Edit', edit_question_answer_path(@question_answer)
\|
= link_to 'Back', question_answers_path