config/routes.rb
QualityCloud::Application.routes.draw do

  resources :question_answers

  resources :template_answers

  resources :question_possible_answers

  resources :questions

  resources :questions_sections

  resources :templates do
    resources :questions
  end

  get 'calls/:call_id/notes' => "call_notes#call_notes"
  resources :call_notes

  get '/users/:user_id/saved_search_tabs' => "saved_search_tabs#user_saved_tabs"
  get '/users/current_user_saved_search_tabs' => "saved_search_tabs#current_user_saved_tabs"
  resources :saved_search_tabs

  match '/organization' => "home#personal", as: :personal_tab
  match '/administration' => "home#administration", as: :administration_tab
  match '/search' => "home#search", as: :search_tab
  get '/settings' => "home#settings", as: :settings_tab
  
  resources :roles do
    member do
      put :set_permissions
    end
  end
  
  match "/permissions" => "roles#permissions"

  resources :groups do
    resources :users, only: [] do
      collection do
        get "/", action: :group_members
      end
    end
  end

  get 'calls/download_calls' => "calls#download_calls"
  get 'calls/:id/stream_video' => "calls#stream_video"
  get 'calls/:id/stream_audio' => "calls#stream_audio"
  match '/calls/search' => "calls#search"
  match '/calls/load_calls' => "calls#load_calls"
  resources :calls do 
    member do
      get :status, :show_popup
    end
  end

  resources :dashboard, only: [ :index ]
  resources :searches, only: [ :index, :create ], controller: :search, path: '/search'

  get '/admin/users/:id/user_avatar/:type' => "users#user_avatar"
  get '/admin/users/user_names' => "users#user_names"
  scope :admin, path: '/admin' do
    resources :users do
      collection { post :import }
    end
  end
  
  devise_for :users, :controllers => { :passwords => "passwords" }
  authenticated :user do
    root :to => 'home#search'
  end
  get "home/email_confirmation" => "home#email_confirmation"

  unauthenticated :user do
    devise_scope :user do 
      get "/" => "devise/sessions#new"
    end
  end

  resources :assigned_roles
  resources :role_accesses

end

app/models/template_answer.rb
class TemplateAnswer < ActiveRecord::Base
 
  # Associations
  belongs_to :template
  belongs_to :user
  belongs_to :call
  has_many :question_answers

  # Attributes
  attr_accessible :total_weight

end

# belongs_to template
# belongs_to call : to be valued
# belongs_to user : who answered the template
# has_many question_answers
# total_weight: as integer

app/controllers/template_answers_controller.rb
class TemplateAnswersController < ApplicationController
  # GET /template_answers
  # GET /template_answers.json
  def index
    @template_answers = TemplateAnswer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @template_answers }
    end
  end

  # GET /template_answers/1
  # GET /template_answers/1.json
  def show
    @template_answer = TemplateAnswer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @template_answer }
    end
  end

  # GET /template_answers/new
  # GET /template_answers/new.json
  def new
    @template_answer = TemplateAnswer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @template_answer }
    end
  end

  # GET /template_answers/1/edit
  def edit
    @template_answer = TemplateAnswer.find(params[:id])
  end

  # POST /template_answers
  # POST /template_answers.json
  def create
    @template_answer = TemplateAnswer.new(params[:template_answer])

    respond_to do |format|
      if @template_answer.save
        format.html { redirect_to @template_answer, notice: 'Template answer was successfully created.' }
        format.json { render json: @template_answer, status: :created, location: @template_answer }
      else
        format.html { render action: "new" }
        format.json { render json: @template_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /template_answers/1
  # PUT /template_answers/1.json
  def update
    @template_answer = TemplateAnswer.find(params[:id])

    respond_to do |format|
      if @template_answer.update_attributes(params[:template_answer])
        format.html { redirect_to @template_answer, notice: 'Template answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @template_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /template_answers/1
  # DELETE /template_answers/1.json
  def destroy
    @template_answer = TemplateAnswer.find(params[:id])
    @template_answer.destroy

    respond_to do |format|
      format.html { redirect_to template_answers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/template_answers_helper.rb
module TemplateAnswersHelper
end

app/views/template_answers/_form.html.haml
= form_for @template_answer do |f|
  - if @template_answer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@template_answer.errors.count, "error")} prohibited this template_answer from being saved:"
      %ul
        - @template_answer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :template
    = f.text_field :template
  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :call
    = f.text_field :call
  .field
    = f.label :total_weight
    = f.number_field :total_weight
  .actions
    = f.submit 'Save'

app/views/template_answers/edit.html.haml
%h1 Editing template_answer

= render 'form'

= link_to 'Show', @template_answer
\|
= link_to 'Back', template_answers_path

app/views/template_answers/index.html.haml
%h1 Listing template_answers

%table
  %tr
    %th Template
    %th User
    %th Call
    %th Total weight
    %th
    %th
    %th

  - @template_answers.each do |template_answer|
    %tr
      %td= template_answer.template
      %td= template_answer.user
      %td= template_answer.call
      %td= template_answer.total_weight
      %td= link_to 'Show', template_answer
      %td= link_to 'Edit', edit_template_answer_path(template_answer)
      %td= link_to 'Destroy', template_answer, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Template answer', new_template_answer_path

app/views/template_answers/new.html.haml
%h1 New template_answer

= render 'form'

= link_to 'Back', template_answers_path

app/views/template_answers/show.html.haml
%p#notice= notice

%p
  %b Template:
  = @template_answer.template
%p
  %b User:
  = @template_answer.user
%p
  %b Call:
  = @template_answer.call
%p
  %b Total weight:
  = @template_answer.total_weight

= link_to 'Edit', edit_template_answer_path(@template_answer)
\|
= link_to 'Back', template_answers_path